// Generated by dia2code
#ifndef STATE__AELEMENTALLOC__H
#define STATE__AELEMENTALLOC__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class AElementAlloc - 
  class AElementAlloc {
    // Associations
    // Operations
  public:
    virtual ~AElementAlloc ();
    virtual Element* newInstance () = 0;
    // Setters and Getters
  };

};

#endif
