// Generated by dia2code
#ifndef STATE__AELEMENTTABALLOC__H
#define STATE__AELEMENTTABALLOC__H


namespace state {
  class ElementTab;
}

#include "ElementTab.h"

namespace state {

  /// class AElementTabAlloc - 
  class AElementTabAlloc {
    // Associations
    // Operations
  public:
    virtual ~AElementTabAlloc ();
    virtual ElementTab* newInstance () = 0;
    // Setters and Getters
  };

};

#endif
