// Generated by dia2code
#ifndef STATE__CELL__H
#define STATE__CELL__H

#include <string>

namespace state {
  class Element;
}

<<<<<<< HEAD
#include "CellTypeID.h"
#include "CellState.h"
=======
#include "ID.h"
>>>>>>> c836bcfb3b8edfe27cda0d2258311ea44d93de9c
#include "Element.h"

namespace state {

  /// class Cell - 
  class Cell : public state::Element {
    // Attributes
  protected:
    std::string resType;
    int resNbr;
    bool occupied     = false;
    // Operations
  public:
    Cell ();
<<<<<<< HEAD
    Cell (CellTypeID type);
    Cell (const Element& elem, CellTypeID type = CellTypeID::SIMPLE, CellState state = CellState::NORMAL);
=======
    Cell (ID type);
    Cell (const Element& elem);
>>>>>>> c836bcfb3b8edfe27cda0d2258311ea44d93de9c
    ~Cell ();
    // Setters and Getters
    const std::string& getResType() const;
    void setResType(const std::string& resType);
    int getResNbr() const;
    void setResNbr(int resNbr);
    bool getOccupied() const;
    void setOccupied(bool occupied);
  };

};

#endif
