// Generated by dia2code
#ifndef STATE__CELLSTATE__H
#define STATE__CELLSTATE__H


namespace state {

  enum CellState {
    NOTCELL     = 0,
    NORMAL     = 1,
    POISONED     = 2,
    PROTECTED     = 3
  };

};

#endif
