// Generated by dia2code
#ifndef STATE__CREATURESID__H
#define STATE__CREATURESID__H


namespace state {

  enum CreaturesID {
    COOKER     = 1,
    BLACKSMITH     = 2,
    LUMBERJACK     = 3,
    MINER     = 4
  };

};

#endif
