// Generated by dia2code
#ifndef STATE__CREATURESTAB__H
#define STATE__CREATURESTAB__H

#include <stdlib.h>
#include <vector>

namespace state {
  class Player;
  class ElementTab;
}

#include "ID.h"
#include "ElementTab.h"
#include "Player.h"

namespace state {

  /// class CreaturesTab - 
  class CreaturesTab : public state::ElementTab {
    // Operations
  public:
    CreaturesTab (size_t width, size_t height);
    ~CreaturesTab ();
    bool isOccupiedByOpp (int i, int j, Player* joueur);
    std::vector<int> moveElement (int i_elem, int j_elem, int new_i_elem, int new_j_elem, int fight);
    void placeElement (int new_i_elem, int new_j_elem, ID creaType);
    bool isEnable (unsigned int i, unsigned int j);
    bool isUnique (std::vector<int>& listeTmp, int i, int j);
    std::vector<int> getFreeCells ();
    bool isSaturated (Player* player);
    std::vector<int> getPlayerCells (Player* player);
    // Setters and Getters
  };

};

#endif
