// Generated by dia2code
#ifndef STATE__CREATURESGROUP__H
#define STATE__CREATURESGROUP__H


namespace state {
  class Player;
  class Element;
  class CreaturesGroup;
}

#include "ID.h"
#include "Element.h"
#include "Player.h"

namespace state {

  /// class CreaturesGroup - 
  class CreaturesGroup : public state::Element {
    // Attributes
  public:
    static int stolenResourceNbr;
  private:
    bool placed;
    Player* joueur;
    // Operations
  public:
<<<<<<< HEAD
    CreaturesGroup (CreaturesID type, int nbrCrea, Player* joueur);
    CreaturesGroup (CreaturesID type, Player* joueur, const Element& elem);
=======
    CreaturesGroup (ID type);
>>>>>>> c836bcfb3b8edfe27cda0d2258311ea44d93de9c
    CreaturesGroup (const Element& elem);
    ~CreaturesGroup ();
    bool getPlaced () const;
    void toPlace (int x, int y);
    bool operator== (CreaturesGroup otherGroup);
    Player* getPlayer ();
    void setPlayer (Player* joueur);
    // Setters and Getters
  };

};

#endif
