// Generated by dia2code
#ifndef STATE__ELEMENTTABFACTORY__H
#define STATE__ELEMENTTABFACTORY__H

#include <map>
#include <stdlib.h>

namespace state {
  class ElementTab;
  class AElementTabAlloc;
  class ElementTabFactory;
}

#include "AElementTabAlloc.h"

namespace state {

  /// class ElementTabFactory - 
  class ElementTabFactory {
    // Associations
    // Attributes
  protected:
    std::map<char,AElementTabAlloc*> list;
    // Operations
  public:
    ~ElementTabFactory ();
    ElementTab* newInstance (char id, size_t height, size_t width) const;
    void registerType (char id, AElementTabAlloc* elem);
    static ElementTabFactory* createDefault ();
    // Setters and Getters
    const std::map<char,AElementTabAlloc*>& getList() const;
    void setList(const std::map<char,AElementTabAlloc*>& list);
  };

};

#endif
