// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class Element;
}

#include "TypeID.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    state::TypeID elemType;
    // Attributes
  protected:
    int x;
    int y;
    int creaturesNbr;
    // Operations
  public:
    Element ();
    Element (TypeID type);
    virtual ~Element ();
    bool operator== (Element otherElement);
    // Setters and Getters
    TypeID getElemType() const;
    void setElemType(TypeID elemType);
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
    int getCreaturesNbr() const;
    void setCreaturesNbr(int creaturesNbr);
  };

};

#endif
