// Generated by dia2code
#ifndef STATE__ELEMENTTAB__H
#define STATE__ELEMENTTAB__H

#include <vector>
#include <memory>
#include <stdlib.h>

namespace state {
  class Element;
}

#include "TypeID.h"
#include "Element.h"

namespace state {

  /// class ElementTab - 
  class ElementTab {
    // Associations
    state::TypeID tabType;
    // Attributes
  private:
    std::vector<std::unique_ptr<Element> > list;
  protected:
    size_t width     = 7;
    size_t height     = 5;
    // Operations
  public:
    ElementTab (size_t width = 7, size_t height = 5);
    ~ElementTab ();
    void resize (size_t width, size_t height);
    const std::unique_ptr<Element>& get (int i, int j = 0) const;
    const std::unique_ptr<Element>& operator ( )  (int i, int j = 0) const;
    const std::unique_ptr<Element>& getByNumber (int number) const;
    void set (Element* elem, int i, int j = 0);
    const std::vector<std::unique_ptr<Element> >& getList () const;
    void poisonCell (bool poison, int i, int j);
    bool isPoisoned (int i, int j);
    bool clearList ();
    // Setters and Getters
    TypeID getTabType() const;
    void setTabType(TypeID tabType);
    const size_t& getWidth() const;
    void setWidth(const size_t& width);
    const size_t& getHeight() const;
    void setHeight(const size_t& height);
  };

};

#endif
