// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class Element;
}

#include "TypeID.h"
#include "ID.h"
#include "CellState.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    state::ID elemType;
    state::CellState cellState;
    // Attributes
  protected:
    int x;
    int y;
    int creaturesNbr;
    TypeID type;
    // Operations
  public:
    Element ();
    Element (TypeID type);
    virtual ~Element ();
    bool operator== (Element otherElement);
    TypeID getType ();
    // Setters and Getters
    ID getElemType() const;
    void setElemType(ID elemType);
    CellState getCellState() const;
    void setCellState(CellState cellState);
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
    int getCreaturesNbr() const;
    void setCreaturesNbr(int creaturesNbr);
    void setType(TypeID type);
  };

};

#endif
