// Generated by dia2code
#ifndef STATE__ELEMENTTABALLOC__H
#define STATE__ELEMENTTABALLOC__H

#include <stdlib.h>

namespace state {
  class ElementTab;
  class AElementTabAlloc;
}

#include "AElementTabAlloc.h"

namespace state {

  /// class ElementTabAlloc - 
  template <  class E,   typename ID>
  class ElementTabAlloc : public state::AElementTabAlloc {
    // Attributes
  protected:
    ID id;
    // Operations
  public:
    ElementTabAlloc (ID id);
    ElementTab* newInstance (size_t height, size_t width);
    // Setters and Getters
    const ID& getId() const;
    void setId(const ID& id);
  };

};

#endif
