// Generated by dia2code
#ifndef STATE__ID__H
#define STATE__ID__H


namespace state {

  enum ID {
    COOKER     = 1,
    BLACKSMITH     = 2,
    LUMBERJACK     = 3,
    MINER     = 4,
    GRASS     = 5,
    DIRT     = 6,
    SAND     = 7,
    BARBECUE     = 8,
    CANDY     = 9,
    POOL     = 10,
    SKY     = 11
  };

};

#endif
