// Generated by dia2code
#ifndef STATE__PLAYERRESOURCES__H
#define STATE__PLAYERRESOURCES__H


namespace state {
  class Player;
}

#include "Player.h"

namespace state {

  /// class PlayerResources - 
  class PlayerResources {
    // Associations
    state::Player Possess;
    // Attributes
  public:
    int wood     = 0;
    int stone     = 0;
    int metal     = 0;
    int food     = 0;
    // Operations
  public:
    int getResource (string type);
    void setResource (string type, int quantity, bool increase);
    // Setters and Getters
    const Player& getPossess() const;
    void setPossess(const Player& Possess);
  };

};

#endif
