// Generated by dia2code
#ifndef STATE__PLAYERRESOURCES__H
#define STATE__PLAYERRESOURCES__H

#include <string>

namespace state {
  class Player;
}

#include "Player.h"

namespace state {

  /// class PlayerResources - 
  class PlayerResources {
    // Associations
    state::Player playerResources;
    // Attributes
  public:
    int wood     = 0;
    int stone     = 0;
    int metal     = 0;
    int food     = 0;
    // Operations
  public:
    PlayerResources ();
    ~PlayerResources ();
    int getResource (std::string type) const;
    void setResource (std::string type, int quantity, bool increase);
    // Setters and Getters
    const Player& getPlayerResources() const;
    void setPlayerResources(const Player& playerResources);
  };

};

#endif
