// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <string>
#include <vector>

namespace state {
  class CreaturesGroup;
}

#include "CreaturesGroup.h"
#include "CreaturesID.h"

namespace state {

  /// class Player - 
  class Player {
    // Associations
    state::CreaturesID clanName;
    // Attributes
  private:
    int cellNbr;
    int zonesNbr;
    int conquestPoints;
    std::vector<std::string> speCellsNames;
    int xLastCell     = 0;
    int yLastCell     = 0;
    std::vector<CreaturesGroup> allCreatures;
    int creaturesLeft;
    // Operations
  public:
    Player ();
    ~Player ();
    int getCellsNbr ();
    int getZonesNbr ();
    int getConquestPoints ();
    int getCreaturesLeft ();
    std::vector<std::string> getSpeCellsNames ();
    int getXLastCell ();
    int getYLastCell ();
    std::vector<CreaturesGroup> getAllCreatures ();
    std::vector<CreaturesGroup> getCreaturesToPlace ();
    void setCellsNbr (int count);
    void setZonesNbr (int count);
    void setConquestPts (int count);
    void setCreaLeft (int count);
    void decreaseCreaLeft ();
    void modifySpeCellsNames (std::string name, bool add);
    void setXLastCell (int x);
    void setYLastCell (int y);
    void setAllCreatures (std::vector<CreaturesGroup> creaList);
    void setAllCreatures (bool add, CreaturesGroup group);
    void setCreaToPlace (std::vector<CreaturesGroup> creaList);
    void setCreaToPlace (bool add, CreaturesGroup group);
    // Setters and Getters
    CreaturesID getClanName() const;
    void setClanName(CreaturesID clanName);
  };

};

#endif
