// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <string>
#include <vector>

#include "CreaturesID.h"

namespace state {

  /// class Player - 
  class Player {
    // Associations
    state::CreaturesID clanName;
    // Attributes
  protected:
    int cellNbr;
    int zonesNbr;
    int conquestPoints;
    int xLastCell     = 0;
    int yLastCell     = 0;
    int creaturesLeft;
    std::vector<std::string> speCellsNames;
    // Operations
  public:
    Player ();
    Player (CreaturesID type);
    ~Player ();
    bool isThereCreatures (int number);
    void decreaseCreaLeft ();
    void modifySpeCellsNames (std::string name, bool add);
    // Setters and Getters
    CreaturesID getClanName() const;
    void setClanName(CreaturesID clanName);
    int getCellNbr() const;
    void setCellNbr(int cellNbr);
    int getZonesNbr() const;
    void setZonesNbr(int zonesNbr);
    int getConquestPoints() const;
    void setConquestPoints(int conquestPoints);
    int getXLastCell() const;
    void setXLastCell(int xLastCell);
    int getYLastCell() const;
    void setYLastCell(int yLastCell);
    int getCreaturesLeft() const;
    void setCreaturesLeft(int creaturesLeft);
    const std::vector<std::string>& getSpeCellsNames() const;
    void setSpeCellsNames(const std::vector<std::string>& speCellsNames);
  };

};

#endif
