// Generated by dia2code
#ifndef STATE__SIMPLECELL__H
#define STATE__SIMPLECELL__H

#include <string>

namespace state {
  class Element;
  class SimpleCell;
  class Cell;
}

#include "ID.h"
#include "CellState.h"
#include "Cell.h"

namespace state {

  /// class SimpleCell - 
  class SimpleCell : public state::Cell {
    // Operations
  public:
    SimpleCell (ID type, std::string resType, int resNbr, int x, int y, CellState state = CellState::NORMAL);
    SimpleCell (const Element& elem);
    ~SimpleCell ();
    bool operator== (SimpleCell otherSimpleCell);
    // Setters and Getters
  };

};

#endif
