// Generated by dia2code
#ifndef STATE__SIMPLECELL__H
#define STATE__SIMPLECELL__H

#include <string>

namespace state {
  class Cell;
}

#include "SimpleCellID.h"
#include "TypeID.h"
#include "Cell.h"

namespace state {

  /// class SimpleCell - 
  class SimpleCell : public state::Cell {
    // Associations
    state::SimpleCellID simpleCellType;
    // Operations
  public:
    SimpleCell (SimpleCellID type, std::string resType, int resNbr);
    ~SimpleCell ();
    const TypeID getTypeID ();
    // Setters and Getters
    SimpleCellID getSimpleCellType() const;
    void setSimpleCellType(SimpleCellID simpleCellType);
  };

};

#endif
