// Generated by dia2code
#ifndef STATE__SPECIALCELL__H
#define STATE__SPECIALCELL__H

#include <string>

namespace state {
  class Cell;
}

#include "Cell.h"
#include "SpecialCellID.h"

namespace state {

  /// class SpecialCell - 
  class SpecialCell : public state::Cell {
    // Associations
    state::SpecialCellID Special cell type;
    // Attributes
  private:
    std::string neededResType;
    int neededResNbr;
    // Operations
  public:
    std::string getResType ();
    int getResNbr ();
    void setResType (std::string resType);
    void setResNbr (int resNbr);
    TypeID const getTypeID ();
    int getx ();
    void setx (int x);
    int gety ();
    void sety (int y);
    // Setters and Getters
    SpecialCellID getSpecial cell type() const;
    void setSpecial cell type(SpecialCellID Special cell type);
  };

};

#endif
