// Generated by dia2code
#ifndef STATE__SPECIALCELL__H
#define STATE__SPECIALCELL__H

#include <string>

namespace state {
  class Element;
  class SpecialCell;
  class Cell;
}

#include "ID.h"
#include "CellState.h"
#include "Cell.h"

namespace state {

  /// class SpecialCell - 
  class SpecialCell : public state::Cell {
    // Operations
  public:
    SpecialCell (ID type, std::string resType, int resNbr, int x, int y, CellState state = CellState::NORMAL);
    SpecialCell (const Element& elem);
    ~SpecialCell ();
    bool operator== (SpecialCell otherSpecialCell);
    // Setters and Getters
  };

};

#endif
