// Generated by dia2code
#ifndef STATE__SPECIALCELL__H
#define STATE__SPECIALCELL__H

#include <string>

namespace state {
  class Cell;
}

#include "SpecialCellID.h"
#include "Cell.h"

namespace state {

  /// class SpecialCell - 
  class SpecialCell : public state::Cell {
    // Associations
    state::SpecialCellID specialCellType;
    // Operations
  public:
    SpecialCell (SpecialCellID type, std::string resType, int resNbr, int x, int y);
    ~SpecialCell ();
    // Setters and Getters
    SpecialCellID getSpecialCellType() const;
    void setSpecialCellType(SpecialCellID specialCellType);
  };

};

#endif
