// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class ElementTab;
  class Player;
}

#include "Player.h"
#include "ElementTab.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    state::Player player;
    // Attributes
  private:
    ElementTab* grid;
    ElementTab* characters;
    int totalCellNbr;
    // Operations
  public:
    State ();
    ~State ();
    ElementTab* getGrid () const;
    ElementTab* getCharacters () const;
    int getCellNbr () const;
    // Setters and Getters
    const Player& getPlayer() const;
    void setPlayer(const Player& player);
  };

};

#endif
