// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include <memory>

namespace state {
  class ElementTab;
  class Player;
}

#include "ElementTab.h"
#include "Player.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  private:
    ElementTab grid;
    ElementTab characters;
    std::unique_ptr<Player> player1;
    std::unique_ptr<Player> player2;
    int totalCellNbr;
    // Operations
  public:
    State ();
    ~State ();
    const ElementTab& getGrid () const;
    ElementTab& getGrid ();
    const ElementTab& getCharacters () const;
    ElementTab& getCharacters ();
    int getCellNbr () const;
    const std::unique_ptr<Player>& getPlayer (int number) const;
    // Setters and Getters
  };

};

#endif
