// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  enum TypeID {
    CREATURESGROUP     = 1,
    SPECIALCELL     = 2,
    SIMPLECELL     = 3
  };

};

#endif
