// Generated by dia2code
#ifndef STATE__CREATURESID__H
#define STATE__CREATURESID__H


namespace state {

  enum CreaturesID {
    COOKERS     = 1,
    BLACKSMITHS     = 2,
    LUMBERJACKS     = 3,
    MINERS     = 4
  };

};

#endif
