// Generated by dia2code
#ifndef RENDER__CELLTILESET__H
#define RENDER__CELLTILESET__H

#include <string>

namespace render {
  class Tile;
};
namespace state {
  class ElementTab;
};
namespace render {
  class TileSet;
}

#include "TileSet.h"

namespace render {

  /// class CellTileSet - 
  class CellTileSet : public render::TileSet {
    // Attributes
  private:
    state::Cell cell;
    // Operations
  public:
    CellTileSet ();
    int getCellWidth () const;
    int getCellHeight () const;
    const std::string getImageFile () const;
    const Tile& getTile (const state::ElementTab& elemTab) const;
    // Setters and Getters
  };

};

#endif
