// Generated by dia2code
#ifndef RENDER__CELLDRAW__H
#define RENDER__CELLDRAW__H

#include <SFML/Graphics.hpp>

namespace render {

  /// class CellDraw - 
  class CellDraw {
    // Attributes
  public:
    sf::VertexArray vertexArray1;
    sf::VertexArray vertexArray2;
    sf::VertexArray vertexArray3;
    sf::VertexArray vertexArray4;
  private:
    int number;
    /// 		
    const int firstXSprite     = 21;
    const int firstYSprite     = 55;
    const int firstXRender     = 120;
    const int firstYRender     = 155;
    // Operations
  public:
    CellDraw (int number);
    // Setters and Getters
  };

};

#endif
