// Generated by dia2code
#ifndef RENDER__CELLSURFACE__H
#define RENDER__CELLSURFACE__H

#include <vector>
#include <memory>
#include <string>

namespace render {
  class Tile;
  class Surface;
  class CellDraw;
}

#include "Surface.h"
#include "CellDraw.h"

namespace render {

  /// class CellSurface - 
  class CellSurface : public render::Surface {
    // Associations
    render::CellDraw traceCell;
    // Attributes
  private:
    std::vector<std::unique_ptr<CellDraw>> cellsList;
    // Operations
  public:
    void loadTexture (const std::string& imgFile);
    void setSpriteLocation (int index, int x, int y);
    void setSpriteTexture (int index, const Tile& tex);
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    void initCells (int count);
    // Setters and Getters
    const CellDraw& getTraceCell() const;
    void setTraceCell(const CellDraw& traceCell);
  };

};

#endif
