// Generated by dia2code
#ifndef RENDER__GRIDTILESET__H
#define RENDER__GRIDTILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class GridTileSet - 
  class GridTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> cells;
    // Operations
  public:
    GridTileSet ();
    int getCellWidth () const;
    int getCellHeight () const;
    const std::string getImageFile () const;
    const Tile& getTile (const state::ElementTab& elemTab) const;
    // Setters and Getters
  };

};

#endif
