// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace render {
  class Tile;
}

namespace render {

  /// class Surface - 
  class Surface {
    // Attributes
  private:
    sf::Texture texture;
    // Operations
  public:
    virtual void loadTexture (const std::string& imgFile) = 0;
    virtual void setSpriteLocation (int index, int x, int y) = 0;
    virtual void setSpriteTexture (int index, const Tile& tex) = 0;
    virtual void draw (sf::RenderTarget& target, sf::RenderStates states) const = 0;
    // Setters and Getters
  };

};

#endif
