// Generated by dia2code
#ifndef RENDER__CELLTABLAYER__H
#define RENDER__CELLTABLAYER__H


namespace state {
  class CellTab;
};
namespace render {
  class ElementTabLayer;
}

#include "ElementTabLayer.h"
#include "state/CellTab.h"

namespace render {

  /// class CellTabLayer - 
  class CellTabLayer : public render::ElementTabLayer {
    // Operations
  public:
    CellTabLayer (const state::CellTab& tab);
    void initSurface ();
    // Setters and Getters
  };

};

#endif
