// Generated by dia2code
#ifndef RENDER__CREATURESTABLAYER__H
#define RENDER__CREATURESTABLAYER__H


namespace state {
  class CreaturesTab;
};
namespace render {
  class ElementTabLayer;
}

#include "ElementTabLayer.h"
#include "state/CreaturesTab.h"

namespace render {

  /// class CreaturesTabLayer - 
  class CreaturesTabLayer : public render::ElementTabLayer {
    // Operations
  public:
    CreaturesTabLayer (const state::CreaturesTab& tab);
    void initSurface ();
    // Setters and Getters
  };

};

#endif
