// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>
#include <memory>

namespace engine {
  class Engine;
}

#include "engine/Engine.h"

namespace ai {

  /// class AI - 
  class AI {
    // Attributes
  protected:
    engine::Engine moteur;
    std::vector<std::unique_ptr<engine::Command> > listCommands;
    // Operations
  public:
    AI ();
    AI (const engine::Engine& moteur);
    virtual run () = 0;
    // Setters and Getters
    const engine::Engine& getMoteur() const;
    void setMoteur(const engine::Engine& moteur);
    const std::vector<std::unique_ptr<engine::Command> >& getListCommands() const;
    void setListCommands(const std::vector<std::unique_ptr<engine::Command> >& listCommands);
  };

};

#endif
