// Generated by dia2code
#ifndef AI__DIRECTION__H
#define AI__DIRECTION__H


namespace ai {

  enum Direction {
    NONE     = 0,
    NORDOUEST     = 1,
    NORDEST     = 2,
    EST     = 3,
    SUDEST     = 4,
    SUDOUEST     = 5,
    OUEST     = 6
  };

};

#endif
