// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H

#include <random>
#include <vector>

namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Attributes
  private:
    std::mt19937 randGen;
    // Operations
  public:
    HeuristicAI (int randomSeed);
    void run (engine::Engine& moteur);
    std::vector<int> moveCellResearch (engine::Engine& moteur);
    // Setters and Getters
  };

};

#endif
