// Generated by dia2code
#ifndef AI__PATHMAP__H
#define AI__PATHMAP__H

#include <vector>
#include <queue>

namespace state {
  class ElementTab;
};
namespace ai {
  class Point;
  class PointCompareWeight;
}

#include "Point.h"
#include "state/ElementTab.h"
#include "PointCompareWeight.h"

namespace ai {

  /// class PathMap - 
  class PathMap {
    // Attributes
  private:
    int width;
    int height;
    std::vector<int> weights;
    std::priority_queue<Point,std::vector<Point>,PointCompareWeight> queue;
    // Operations
  public:
    PathMap (const state::ElementTab& grid);
    int getWeight (const Point& p) const;
    void setWeight (const Point& p, int weight);
    std::vector<int>& getWeights () const;
    void init (const state::ElementTab& grid);
    void addSink (Point p);
    void update (const state::ElementTab& grid);
    // Setters and Getters
  };

};

#endif
