// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeID {
    NEWGAME     = 1,
    MOVE     = 2,
    PLACE     = 3,
    POISON     = 4,
    PROTECTED     = 5,
    SPECIAL     = 6
  };

};

#endif
