// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeID {
    NEWGAME     = 1,
    MOVE     = 2,
    POISON     = 3,
    PROTECTED     = 4
  };

};

#endif
