// Generated by dia2code
#ifndef ENGINE__FIGHTCOMMAND__H
#define ENGINE__FIGHTCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class FightCommand - 
  class FightCommand : public engine::Command {
    // Attributes
  protected:
    int creaPl1;
    int creaPl2;
    int cell;
    // Operations
  public:
    FightCommand (int creatures1, int creatures2, int cell);
    bool fightProcess (state::State& state);
    void gainConquest (state::State& state);
    CommandTypeID getTypeID () const;
    void execute (state::State& state);
    // Setters and Getters
    int getCreaPl1() const;
    void setCreaPl1(int creaPl1);
    int getCreaPl2() const;
    void setCreaPl2(int creaPl2);
    int getCell() const;
    void setCell(int cell);
  };

};

#endif
