// Generated by dia2code
#ifndef ENGINE__MOVECOMMAND__H
#define ENGINE__MOVECOMMAND__H

#include <memory>
#include <vector>

namespace engine {
  class Fight;
};
namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "Fight.h"
#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class MoveCommand - 
  class MoveCommand : public engine::Command {
    // Associations
    // Attributes
  protected:
    std::shared_ptr<Fight> fight;
    std::vector<int> initPos;
    std::vector<int> finalPos;
    int player;
    // Operations
  public:
    MoveCommand ();
    MoveCommand (int init_i, int init_j, int final_i, int final_j, int player);
    CommandTypeID getTypeID () const;
    void execute (state::State& state);
    // Setters and Getters
    const std::shared_ptr<Fight>& getFight() const;
    void setFight(const std::shared_ptr<Fight>& fight);
    const std::vector<int>& getInitPos() const;
    void setInitPos(const std::vector<int>& initPos);
    const std::vector<int>& getFinalPos() const;
    void setFinalPos(const std::vector<int>& finalPos);
    int getPlayer() const;
    void setPlayer(int player);
  };

};

#endif
