// Generated by dia2code
#ifndef ENGINE__MOVECHARCOMMAND__H
#define ENGINE__MOVECHARCOMMAND__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class MoveCharCommand - 
  class MoveCharCommand : public engine::Command {
    // Attributes
  protected:
    std::vector<int> creatures;
    int newI;
    int newJ;
    // Operations
  public:
    MoveCharCommand (int i_crea, int j_crea, int newI, int newJ);
    CommandTypeID getTypeID () const;
    void execute (state::State& state);
    // Setters and Getters
    const std::vector<int>& getCreatures() const;
    void setCreatures(const std::vector<int>& creatures);
    int getNewI() const;
    void setNewI(int newI);
    int getNewJ() const;
    void setNewJ(int newJ);
  };

};

#endif
