// Generated by dia2code
#ifndef ENGINE__MOVECHARCOMMAND__H
#define ENGINE__MOVECHARCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class MoveCharCommand - 
  class MoveCharCommand : public engine::Command {
    // Attributes
  protected:
    int creatures;
    // Operations
  public:
    MoveCharCommand (int c);
    CommandTypeID getTypeID () const;
    void execute (state::State& state);
    // Setters and Getters
    int getCreatures() const;
    void setCreatures(int creatures);
  };

};

#endif
