// Generated by dia2code
#ifndef ENGINE__NEWGAMECOMMAND__H
#define ENGINE__NEWGAMECOMMAND__H

#include <stack>
#include <memory>

namespace engine {
  class Action;
};
namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "Action.h"
#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class NewGameCommand - 
  class NewGameCommand : public engine::Command {
    // Operations
  public:
    NewGameCommand ();
    void execute (std::stack<std::shared_ptr<Action>>& pile, state::State& state);
    CommandTypeID getTypeID () const;
    // Setters and Getters
  };

};

#endif
