// Generated by dia2code
#ifndef ENGINE__NEWGAMECOMMAND__H
#define ENGINE__NEWGAMECOMMAND__H

#include <stack>
#include <memory>
#include <json/json.h>

namespace engine {
  class Action;
};
namespace state {
  class State;
};
namespace engine {
  class NewGameCommand;
  class Command;
}

#include "Action.h"
#include "Command.h"

namespace engine {

  /// class NewGameCommand - 
  class NewGameCommand : public engine::Command {
    // Operations
  public:
    NewGameCommand ();
    void execute (std::stack<std::shared_ptr<Action>>& pile, state::State& state);
    void serialize (Json::Value& out, int nTour) const;
    static NewGameCommand* deserialize (const Json::Value& in);
    // Setters and Getters
  };

};

#endif
