// Generated by dia2code
#ifndef ENGINE__NEWGAMECOMMAND__H
#define ENGINE__NEWGAMECOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class NewGameCommand - 
  class NewGameCommand : public engine::Command {
    // Operations
  public:
    NewGameCommand ( );
    CommandTypeID getTypeID () const;
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
