// Generated by dia2code
#ifndef ENGINE__PLACECOMMAND__H
#define ENGINE__PLACECOMMAND__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/ID.h"
#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class PlaceCommand - 
  class PlaceCommand : public engine::Command {
    // Attributes
  protected:
    std::vector<int> finalPos;
    int player;
    state::ID creaType;
    // Operations
  public:
    PlaceCommand (int i_final, int j_final, int player, state::ID type);
    CommandTypeID getTypeID () const;
    void execute (state::State& state);
    // Setters and Getters
    const std::vector<int>& getFinalPos() const;
    void setFinalPos(const std::vector<int>& finalPos);
    int getPlayer() const;
    void setPlayer(int player);
    state::ID getCreaType() const;
    void setCreaType(state::ID creaType);
  };

};

#endif
