// Generated by dia2code
#ifndef ENGINE__PLACECOMMAND__H
#define ENGINE__PLACECOMMAND__H

#include <vector>
#include <stack>
#include <memory>

namespace engine {
  class Action;
};
namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/ID.h"
#include "Action.h"
#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class PlaceCommand - 
  class PlaceCommand : public engine::Command {
    // Attributes
  protected:
    std::vector<int> pos;
    state::ID creaType;
    // Operations
  public:
    PlaceCommand (int i, int j, int player, state::ID type);
    void execute (std::stack<std::shared_ptr<Action> >& pile, state::State& state);
    CommandTypeID getTypeID () const;
    // Setters and Getters
    const std::vector<int>& getPos() const;
    void setPos(const std::vector<int>& pos);
    state::ID getCreaType() const;
    void setCreaType(state::ID creaType);
  };

};

#endif
