// Generated by dia2code
#ifndef ENGINE__PLACECOMMAND__H
#define ENGINE__PLACECOMMAND__H

#include <vector>
#include <stack>
#include <memory>
#include <json/json.h>

namespace engine {
  class Action;
};
namespace state {
  class State;
};
namespace engine {
  class PlaceCommand;
  class Command;
}

#include "state/ID.h"
#include "Action.h"
#include "Command.h"

namespace engine {

  /// class PlaceCommand - 
  class PlaceCommand : public engine::Command {
    // Attributes
  protected:
    std::vector<int> finalPos;
    state::ID creaType;
    // Operations
  public:
    PlaceCommand (int i, int j, int player, state::ID type);
    void execute (std::stack<std::shared_ptr<Action>>& pile, state::State& state);
    void serialize (Json::Value& out, int nTour) const;
    static PlaceCommand* deserialize (const Json::Value& in);
    // Setters and Getters
    const std::vector<int>& getFinalPos() const;
    void setFinalPos(const std::vector<int>& finalPos);
    state::ID getCreaType() const;
    void setCreaType(state::ID creaType);
  };

};

#endif
