// Generated by dia2code
#ifndef ENGINE__PLACEACTION__H
#define ENGINE__PLACEACTION__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "state/ID.h"
#include "Action.h"

namespace engine {

  /// class PlaceAction - 
  class PlaceAction : public engine::Action {
    // Attributes
  protected:
    std::vector<int> finalPos;
    int player;
    state::ID creaType;
    // Operations
  public:
    PlaceAction (int i_final, int j_final, int player, state::ID type);
    void apply (state::State& state);
    void undo (state::State& etat);
    // Setters and Getters
    const std::vector<int>& getFinalPos() const;
    void setFinalPos(const std::vector<int>& finalPos);
    int getPlayer() const;
    void setPlayer(int player);
    state::ID getCreaType() const;
    void setCreaType(state::ID creaType);
  };

};

#endif
