// Generated by dia2code
#ifndef ENGINE__POISONACTION__H
#define ENGINE__POISONACTION__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class PoisonAction - 
  class PoisonAction : public engine::Action {
    // Attributes
  protected:
    std::vector<int> cell;
    // Operations
  public:
    PoisonAction (int i_cell, int j_cell);
    bool isPoisoned (state::State& state);
    void killCreatures (state::State& state);
    void apply (state::State& state);
    void undo (state::State& etat);
    // Setters and Getters
    const std::vector<int>& getCell() const;
    void setCell(const std::vector<int>& cell);
  };

};

#endif
