// Generated by dia2code
#ifndef ENGINE__POISONACTION__H
#define ENGINE__POISONACTION__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Action;
};
namespace state {
  class CreaturesGroup;
}

#include "state/ID.h"
#include "Action.h"
#include "state/CreaturesGroup.h"

namespace engine {

  /// class PoisonAction - 
  class PoisonAction : public engine::Action {
    // Attributes
  protected:
    std::vector<int> cell;
    int nbrCreaBegin;
    state::ID typeCreaBegin;
    int playerBegin;
    // Operations
  public:
    PoisonAction (int i_cell, int j_cell, state::ID typeCreatures, int player);
    bool isPoisoned (state::State& state);
    void killCreatures (state::State& state);
    void apply (state::State& state);
    void undo (state::State& etat);
    // Setters and Getters
    const std::vector<int>& getCell() const;
    void setCell(const std::vector<int>& cell);
    int getNbrCreaBegin() const;
    void setNbrCreaBegin(int nbrCreaBegin);
    state::ID getTypeCreaBegin() const;
    void setTypeCreaBegin(state::ID typeCreaBegin);
    int getPlayerBegin() const;
    void setPlayerBegin(int playerBegin);
  };

};

#endif
