// Generated by dia2code
#ifndef ENGINE__POISONCOMMAND__H
#define ENGINE__POISONCOMMAND__H

#include <stack>
#include <memory>

namespace engine {
  class Action;
};
namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "Action.h"
#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class PoisonCommand - 
  class PoisonCommand : public engine::Command {
    // Attributes
  protected:
    int target;
    // Operations
  public:
    PoisonCommand (int i, int j);
    void execute (std::stack<std::shared_ptr<Action>>& pile, state::State& state);
    CommandTypeID getTypeID () const;
    // Setters and Getters
    int getTarget() const;
    void setTarget(int target);
  };

};

#endif
