// Generated by dia2code
#ifndef ENGINE__PROTECTEDCOMMAND__H
#define ENGINE__PROTECTEDCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class ProtectedCommand - 
  class ProtectedCommand : public engine::Command {
    // Attributes
  protected:
    int cell;
    // Operations
  public:
    ProtectedCommand (int cell);
    void protectProcess (state::State& state);
    CommandTypeID getTypeID () const;
    void execute (state::State& state);
    // Setters and Getters
    int getCell() const;
    void setCell(int cell);
  };

};

#endif
