// Generated by dia2code
#ifndef ENGINE__PROTECTEDACTION__H
#define ENGINE__PROTECTEDACTION__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class ProtectedAction - 
  class ProtectedAction : public engine::Action {
    // Attributes
  protected:
    std::vector<int> cell;
    // Operations
  public:
    ProtectedAction (int i_cell, int j_cell);
    void protectProcess (state::State& state);
    void apply (state::State& state);
    bool isProtected (state::State& state);
    void undo (state::State& etat);
    // Setters and Getters
    const std::vector<int>& getCell() const;
    void setCell(const std::vector<int>& cell);
  };

};

#endif
