// Generated by dia2code
#ifndef ENGINE__PROTECTEDCOMMAND__H
#define ENGINE__PROTECTEDCOMMAND__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeID.h"
#include "Command.h"

namespace engine {

  /// class ProtectedCommand - 
  class ProtectedCommand : public engine::Command {
    // Attributes
  protected:
    std::vector<int> cell;
    // Operations
  public:
    ProtectedCommand (int i_cell, int j_cell);
    void protectProcess (state::State& state);
    CommandTypeID getTypeID () const;
    void execute (state::State& state);
    bool isProtected (state::State& state);
    // Setters and Getters
    const std::vector<int>& getCell() const;
    void setCell(const std::vector<int>& cell);
  };

};

#endif
