// Generated by dia2code
#ifndef ENGINE__SPECIALCELLCOMMAND__H
#define ENGINE__SPECIALCELLCOMMAND__H

#include <vector>
#include <stack>
#include <memory>
#include <json/json.h>
#include <string>

namespace engine {
  class Action;
};
namespace state {
  class State;
};
namespace engine {
  class SpecialCellCommand;
  class Command;
}

#include "SpecialTypeID.h"
#include "Action.h"
#include "Command.h"

namespace engine {

  /// class SpecialCellCommand - 
  class SpecialCellCommand : public engine::Command {
    // Associations
    engine::SpecialTypeID specialType;
    // Attributes
  protected:
    std::vector<int> initPos;
    std::vector<int> finalPos;
    // Operations
  public:
    SpecialCellCommand (int init_i, int init_j, int target_i, int target_j, int player, SpecialTypeID type);
    void execute (std::stack<std::shared_ptr<Action>>& pile, state::State& state);
    void serialize (Json::Value& out, int nTour) const;
    static SpecialCellCommand* deserialize (const Json::Value& in);
    static SpecialTypeID translateSpecialType (std::string nomType);
    // Setters and Getters
    SpecialTypeID getSpecialType() const;
    void setSpecialType(SpecialTypeID specialType);
    const std::vector<int>& getInitPos() const;
    void setInitPos(const std::vector<int>& initPos);
    const std::vector<int>& getFinalPos() const;
    void setFinalPos(const std::vector<int>& finalPos);
  };

};

#endif
