// Generated by dia2code
#ifndef ENGINE__SPECIALTYPEID__H
#define ENGINE__SPECIALTYPEID__H


namespace engine {

  enum SpecialTypeID {
    SKY     = 1,
    SUGAR     = 2,
    BARBECUE     = 3,
    POOL     = 4
  };

};

#endif
