// Generated by dia2code
#ifndef SERVER__GAMESERVICE__H
#define SERVER__GAMESERVICE__H

#include <json/json.h>
#include <string>

namespace server {
  class AbstractService;
}

#include "AbstractService.h"

namespace server {

  /// class GameService - 
  class GameService : public server::AbstractService {
    // Operations
  public:
    GameService ();
    HttpStatus const get (Json::Value& out, std::string id);
    // Setters and Getters
  };

};

#endif
