// Generated by dia2code
#ifndef SERVER__GAME__H
#define SERVER__GAME__H

#include <vector>

namespace engine {
  class Engine;
  class Command;
}

#include "engine/Command.h"
#include "engine/Engine.h"
#include "GameStatus.h"

namespace server {

  /// class Game - 
  class Game {
    // Associations
    server::GameStatus status;
    // Attributes
  public:
    int beginner     = 0;
    int party;
    int currentPlayer;
  private:
    engine::Engine* moteur;
  protected:
    std::vector<engine::Command> listCommands;
    // Operations
  public:
    Game ();
    ~Game ();
    engine::Engine* getEngine ();
    void run ();
    // Setters and Getters
    GameStatus getStatus() const;
    void setStatus(GameStatus status);
    const std::vector<engine::Command>& getListCommands() const;
    void setListCommands(const std::vector<engine::Command>& listCommands);
  };

};

#endif
