// Generated by dia2code
#ifndef SERVER__GAME__H
#define SERVER__GAME__H

#include <json/json.h>

namespace engine {
  class Engine;
  class Command;
}

#include "engine/Command.h"
#include "engine/Engine.h"
#include "GameStatus.h"

namespace server {

  /// class Game - 
  class Game {
    // Associations
    server::GameStatus status;
    // Attributes
  public:
    int beginner     = 0;
    int party;
    int currentPlayer;
    Json::Value listCommands;
    int idmax     = 0;
  private:
    engine::Engine* moteur;
    // Operations
  public:
    Game ();
    ~Game ();
    engine::Engine* getEngine ();
    void run ();
    // Setters and Getters
    GameStatus getStatus() const;
    void setStatus(GameStatus status);
  };

};

#endif
