// Generated by dia2code
#ifndef SERVER__USERSERVICE__H
#define SERVER__USERSERVICE__H

#include <json/json.h>

namespace server {
  class UserGame;
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"
#include "UserGame.h"

namespace server {

  /// class UserService - 
  class UserService : public server::AbstractService {
    // Associations
    // Attributes
  protected:
    UserGame& userGame;
    // Operations
  public:
    UserService (UserGame& userGame);
    HttpStatus get (Json::Value& out, int id) const;
    HttpStatus post (const Json::Value& in, int id);
    HttpStatus put (Json::Value& out, const Json::Value& in);
    HttpStatus remove (int id);
    // Setters and Getters
    UserGame& getUserGame() const;
    void setUserGame(const UserGame&& userGame);
  };

};

#endif
