// Generated by dia2code
#ifndef SERVER__USER__H
#define SERVER__USER__H

#include <string>

#include "state/CreaturesID.h"

namespace server {

  /// class User - 
  class User {
    // Attributes
  public:
    std::string name;
    state::CreaturesID creatures;
    // Operations
  public:
    User (std::string name, state::CreaturesID creatures);
    // Setters and Getters
  };

};

#endif
