// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/CommandTypeID.h"
#include "engine/Action.h"
#include "engine/Command.h"
#include "engine/Engine.h"
#include "engine/Fight.h"
#include "engine/PoisonAction.h"
#include "engine/NewGameAction.h"
#include "engine/ProtectedAction.h"
#include "engine/MoveAction.h"
#include "engine/PlaceAction.h"
#include "engine/SpecialCellAction.h"
#include "engine/MoveCommand.h"
#include "engine/PlaceCommand.h"
#include "engine/NewGameCommand.h"
#include "engine/ProtectedCommand.h"
#include "engine/PoisonCommand.h"
#include "engine/SpecialTypeID.h"
#include "engine/SpecialCellCommand.h"
#endif
