// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/CommandTypeID.h"
#include "engine/Command.h"
#include "engine/Engine.h"
#include "engine/FightCommand.h"
#include "engine/MoveCharCommand.h"
#include "engine/PoisonCommand.h"
#include "engine/NewGameCommand.h"
#include "engine/ProtectedCommand.h"
#endif
