// Generated by dia2code
#ifndef CLIENT__SUPERENGINE__H
#define CLIENT__SUPERENGINE__H

#include <memory>

namespace engine {
  class Engine;
}

#include "engine/Engine.h"

namespace client {

  /// class SuperEngine - 
  class SuperEngine : public engine::Engine {
    // Operations
  public:
    void addCommand (int priority, std::shared_ptr<state::Command> cmd);
    // Setters and Getters
  };

};

#endif
