// Generated by dia2code
#ifndef CLIENT__SUPERENGINE__H
#define CLIENT__SUPERENGINE__H

#include <memory>
#include <string>

namespace engine {
  class Command;
  class Engine;
}

#include "engine/Command.h"
#include "engine/CommandTypeID.h"
#include "engine/Engine.h"

namespace client {

  /// class SuperEngine - 
  class SuperEngine : public engine::Engine {
    // Operations
  public:
    void addCommand (int priority, std::shared_ptr<engine::Command> cmd);
    std::string convertCommandTypeToString (engine::CommandTypeID commandType);
    // Setters and Getters
  };

};

#endif
