// Generated by dia2code
#ifndef STATE__CELL__H
#define STATE__CELL__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class Cell - 
  class Cell : public state::Element {
    // Operations
  public:
// Setters and Getters
    int getx ();
    void setx (int x);
    int gety ();
    void sety (int y);
    
  };

};

#endif
