// Generated by dia2code
#ifndef STATE__CELLSTATE__H
#define STATE__CELLSTATE__H


namespace state {
  class Cell;
}

#include "Cell.h"

namespace state {

  enum CellState {
    NORMAL     = 1,
    POISONED     = 2,
    PROTECTED     = 3
  };

};

#endif
