// Generated by dia2code
#ifndef STATE__CELL__H
#define STATE__CELL__H


namespace state {
  class Element;
  class CreaturesGroup;
}

#include "Element.h"
#include "CreaturesGroup.h"

namespace state {

  /// class Cell - 
  class Cell : public state::Element {
    // Associations
    state::CreaturesGroup where;
    // Operations
  public:
    virtual int getx () = 0;
    virtual void setx (int x) = 0;
    virtual int gety () = 0;
    virtual void sety (int y) = 0;
    virtual TypeID const getTypeID () = 0;
    // Setters and Getters
    const CreaturesGroup& getWhere() const;
    void setWhere(const CreaturesGroup& where);
  };

};

#endif
