// Generated by dia2code
#ifndef STATE__CLANNAMEID__H
#define STATE__CLANNAMEID__H


namespace state {

  enum ClanNameID {
    COOKERS     = 1,
    BLACKSMITHS     = 2,
    LUMBERJACKS     = 3,
    MINERS     = 4
  };

};

#endif
