// Generated by dia2code
#ifndef STATE__CREATURESGROUP__H
#define STATE__CREATURESGROUP__H


namespace state {
  class Element;
}

#include "Element.h"
#include "CreaturesID.h"

namespace state {

  /// class CreaturesGroup - 
  class CreaturesGroup : public state::Element {
    // Associations
    state::CreaturesID Creatures_type;
    // Attributes
  private:
    const int stolenResourceNbr = 2;
    bool placed;
    // Operations
  public:
    int getx ();
    void setx (int x);
    int gety ();
    void sety (int y);
    TypeID const getTypeID ();
    bool getplaced ();
    void place (int x, int y);
    // Setters and Getters
    CreaturesID getCreatures_type() const;
    void setCreatures_type(CreaturesID Creatures_type);
  };

};

#endif
