// Generated by dia2code
#ifndef STATE__CREATURESID__H
#define STATE__CREATURESID__H


namespace state {

  enum CreaturesID {
    LUMBERJACKS     = 1,
    MINERS     = 2,
    BLACKSMITHS     = 3,
    COOKERS     = 4
  };

};

#endif
