// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <string>
#include <vector>

namespace state {
  class CreaturesGroup;
}

#include "CreaturesGroup.h"
#include "ClanNameID.h"

namespace state {

  /// class Player - 
  class Player {
    // Associations
    state::CreaturesGroup possess;
    state::ClanNameID identify;
    // Attributes
  private:
    int cellNbr;
    int zonesNbr;
    int conquestPoints;
    int creaturesLeft;
    std::vector<std::string> speCellsNames;
    int xLastCell     = 0;
    int yLastCell     = 0;
    // Operations
  public:
    Player ();
    ~Player ();
    int getCellsNbr ();
    int getZonesNbr ();
    int getConquestPoints ();
    int getCreaturesLeft ();
    std::vector<std::string> getSpeCellsNames ();
    int getXLastCell ();
    int getYLastCell ();
    void setCellsNbr (int count);
    void setZonesNbr (int count);
    void setConquestPts (int count);
    void setCreaLeft (int count);
    void decreaseCreaLeft ();
    void modifySpeCellsNames (std::string name, bool add);
    void setXLastCell (int x);
    void setYLastCell (int y);
    // Setters and Getters
    const CreaturesGroup& getPossess() const;
    void setPossess(const CreaturesGroup& possess);
    ClanNameID getIdentify() const;
    void setIdentify(ClanNameID identify);
  };

};

#endif
