// Generated by dia2code
#ifndef STATE__PLAYERRESOURCES__H
#define STATE__PLAYERRESOURCES__H


namespace state {
  class Player;
}

#include "Player.h"

namespace state {

  struct PlayerResources {
    int wood     = 0;
    int stone     = 0;
    int metal     = 0;
    int food     = 0;
  };

};

#endif
