// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <vector>

namespace state {
  class Zone;
  class ElementTab;
}

#include "Zone.h"
#include "ElementTab.h"
#include "ClanNameID.h"

namespace state {

  /// class Player - 
  class Player {
    // Associations
    state::ElementTab Creatures to put on the map;
    state::ClanNameID Identify;
    // Attributes
  private:
    int cellNbr;
    int zonesNbr;
    int conquestPoints;
    int creaturesLeft;
    std::vector<std::String> speCellsNames;
    int xLastCell     = 0;
    int yLastCell     = 0;
    std::vector<Zone> zone;
    // Operations
  public:
    int getCellsNbr ();
    int getZonesNbr ();
    int getConquestPoints ();
    int getCreaturesLeft ();
    std::vector<std::String> getSpeCellsNames ();
    int getXLastCell ();
    int getYLastCell ();
    void setCellsNbr (int count);
    void setZonesNbr (int count);
    void setConquestPts (int count);
    void setCreaLeft (int count);
    void decreaseCreaLeft (bool decrease);
    void modifySpeCellsNames (string name, bool add);
    void setXLastCell (int x);
    void setYLastCell (int y);
    // Setters and Getters
    const ElementTab& getCreatures to put on the map() const;
    void setCreatures to put on the map(const ElementTab& Creatures to put on the map);
    ClanNameID getIdentify() const;
    void setIdentify(ClanNameID Identify);
  };

};

#endif
