// Generated by dia2code
#ifndef STATE__SIMPLECELL__H
#define STATE__SIMPLECELL__H

#include <vector>

namespace state {
  class Cell;
  class Zone;
}

#include "Cell.h"
#include "SimpleCellID.h"
#include "Zone.h"

namespace state {

  /// class SimpleCell - 
  class SimpleCell : public state::Cell {
    // Associations
    state::SimpleCellID Simple cell type;
    state::Zone Cells included in a zone;
    // Attributes
  private:
    std::vector<string> genResType;
    std::vector<int> genResNbr;
    // Operations
  public:
    std::vector<string> getResType ();
    std::vector<int> getResNbr ();
    void addResType (string resType);
    void addResNbr (int resNbr);
    // Setters and Getters
    SimpleCellID getSimple cell type() const;
    void setSimple cell type(SimpleCellID Simple cell type);
    const Zone& getCells included in a zone() const;
    void setCells included in a zone(const Zone& Cells included in a zone);
  };

};

#endif
