// Generated by dia2code
#ifndef STATE__SIMPLECELL__H
#define STATE__SIMPLECELL__H

#include <vector>
#include <string>

namespace state {
  class Cell;
}

#include "Cell.h"
#include "SimpleCellID.h"

namespace state {

  /// class SimpleCell - 
  class SimpleCell : public state::Cell {
    // Associations
    state::SimpleCellID Simple cell type;
    // Attributes
  private:
    std::vector<string> genResType;
    std::vector<int> genResNbr;
    // Operations
  public:
    std::vector<string> getResType ();
    std::vector<int> getResNbr ();
    void addResType (std::string resType);
    void addResNbr (int resNbr);
    TypeID const getTypeID ();
    int getx ();
    void setx (int x);
    int gety ();
    void sety (int y);
    // Setters and Getters
    SimpleCellID getSimple cell type() const;
    void setSimple cell type(SimpleCellID Simple cell type);
  };

};

#endif
