// Generated by dia2code
#ifndef STATE__SIMPLECELLID__H
#define STATE__SIMPLECELLID__H


namespace state {

  enum SimpleCellID {
    GRASS     = 1,
    DIRT     = 2,
    SAND     = 3
  };

};

#endif
