// Generated by dia2code
#ifndef STATE__SPECIALCELL__H
#define STATE__SPECIALCELL__H


namespace state {
  class Cell;
}

#include "Cell.h"
#include "SpecialCellID.h"

namespace state {

  /// class SpecialCell - 
  class SpecialCell : public state::Cell {
    // Associations
    state::SpecialCellID SpecialCell_type;
    // Attributes
  private:
    string neededResType;
    int neededResNbr;
    // Operations
  public:
    string getResType ();
    int getResNbr ();
    void setResType (string resType);
    void setResNbr (int resNbr);
    // Setters and Getters
    SpecialCellID getSpecialCell_type() const;
    void setSpecialCell_type(SpecialCellID SpecialCell_type);
  };

};

#endif
