// Generated by dia2code
#ifndef STATE__SPECIALCELL__H
#define STATE__SPECIALCELL__H

#include <string>

namespace state {
  class Cell;
}

#include "SpecialCellID.h"
#include "Cell.h"

namespace state {

  /// class SpecialCell - 
  class SpecialCell : public state::Cell {
    // Associations
    state::SpecialCellID specialCellType;
    // Attributes
  private:
    std::string neededResType;
    int neededResNbr;
    // Operations
  public:
    SpecialCell (SpecialCellID type, std::string resType, int resNbr);
    ~SpecialCell ();
    std::string getResType ();
    int getResNbr ();
    void setResType (std::string resType);
    void setResNbr (int resNbr);
    TypeID const getTypeID ();
    // Setters and Getters
    SpecialCellID getSpecialCellType() const;
    void setSpecialCellType(SpecialCellID specialCellType);
  };

};

#endif
