// Generated by dia2code
#ifndef STATE__SPECIALCELLID__H
#define STATE__SPECIALCELLID__H


namespace state {

  enum SpecialCellID {
    BARBECUE     = 1,
    CANDY     = 2,
    POOL     = 3,
    SKY     = 4
  };

};

#endif
