// Generated by dia2code
#ifndef STATE__ZONE__H
#define STATE__ZONE__H

#include <vector>

namespace state {
  class SimpleCell;
  class Player;
}

#include "SimpleCell.h"
#include "Player.h"

namespace state {

  /// class Zone - 
  class Zone {
    // Associations
    state::Player Players' zones;
    // Attributes
  private:
    int cellNbr;
    std::vector<SimpleCell> cellList;
    int j1Nbr;
    int j2Nbr;
    // Operations
  public:
    Player getOwner ();
    void addToCellList (SimpleCell cell);
    // Setters and Getters
    const Player& getPlayers' zones() const;
    void setPlayers' zones(const Player& Players' zones);
  };

};

#endif
