// Generated by dia2code
#ifndef CELL__H
#define CELL__H

/// class Cell - 
class Cell : public Element {
  // Operations
public:
  int getx ();
  void setx (int x);
  int gety ();
  void sety (int y);
  // Setters and Getters
};

#endif
